[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self'; connect-src 'self'  https://api.dscvr.one https://api1.stg.dscvr.one https://*.helius-rpc.com; https://*.solana.com/ ; font-src 'self';"
